name: Release

on:
    push:
        tags:
            - "v*"

jobs:
    build-and-release:
        runs-on: ubuntu-latest
        steps:
            - name: 签出代码
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: 下载git-chglog
              run: |
                  go install github.com/git-chglog/git-chglog/cmd/git-chglog@latest

            - name: 生成 CHANGELOG
              run: |
                  # 生成当前 tag 的变更日志
                  git-chglog -o CHANGELOG.md ${{ github.ref_name }}

            - name: 下载 go SDK
              uses: actions/setup-go@v5
              with:
                  go-version: "1.23.6"

            - name: 构建 Windows x86-64
              run: |
                  GOOS=windows GOARCH=amd64 go build -o bin/app-windows-amd64.exe .
                  zip -j bin/app-windows-amd64.zip bin/app-windows-amd64.exe

            - name: 构建 Linux amd64
              run: |
                  GOOS=linux GOARCH=amd64 go build -o bin/app-linux-amd64 .
                  tar -czvf bin/app-linux-amd64.tar.gz -C bin app-linux-amd64

            - name: 创建 Release
              uses: softprops/action-gh-release@v1
              with:
                  tag_name: ${{ github.ref_name }}
                  name: Release ${{ github.ref_name }}
                  body: |
                      $(cat CHANGELOG.md)
                  files: |
                      bin/app-windows-amd64.zip
                      bin/app-linux-amd64.tar.gz
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
